// Generated by CoffeeScript 1.3.3
(function() {
  var active, button, buttons, clickButtonSetup, fontColor, hideButtons, makeActive, makeInactive, _i, _len;

  fontColor = '#ffffff';

  buttons = ["#csc", "#phl", "#contact", "#about", "#solutions"];

  active = "#about";

  makeActive = function(button) {
    var other_button, _i, _len;
    active = button;
    $(button).show("fast");
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      other_button = buttons[_i];
      if (other_button !== button) {
        makeInactive(other_button);
      }
    }
    return $(button + "Button").addClass("active");
  };

  makeInactive = function(button) {
    $(button + "Button").removeClass("active");
    return $(button).hide("fast");
  };

  makeActive("#solutions");



  $("h1").mouseover(function() {
    return $(this).animate({
      color: '#1C8FE1'
    }, 200).mouseout(function() {
      return $(this).animate({
        color: '#000000'
      }, 200);
    });
  });



}).call(this);
